services:
  application:
    environment:
      - APP_URL=${APP_URL}
      - CONSOLE_HOST=${CONSOLE_HOST}
      - API_HOST=${API_HOST}
      - API_NAMESPACE=${API_NAMESPACE}
      - API_SECURE=${API_SECURE}
  
  socket:
    environment:
      - SOCKETCLUSTER_HOST=${SOCKETCLUSTER_HOST}
      - SOCKETCLUSTER_PORT=${SOCKETCLUSTER_PORT}
      - SOCKETCLUSTER_SECURE=${SOCKETCLUSTER_SECURE}